name: Publish Terraform Module
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish to Terraform Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Confirm Release Tag
        run: echo "Tag ${{ github.ref }} pushed. Terraform Registry will pick up new version."